modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="bookofdragons" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Book of Dragons" #mandatory
credits="Zae, Coolrex, Tazz" #optional
authors="Coda" #optional
description=''''''
[[dependencies.bookofdragons]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.bookofdragons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
